### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by MOZGIII** [falceeffect/UGlobalHotkey#5]
Can you provide a usage example for this lib?

**Comment by falceeffect** [comment]
Check readme

**Comment by MOZGIII** [comment]
And what about building and using the lib? am I supposed to copy the code over or build and link with the lib?
It seems like the way it's supposed to be used is via building and linking with the lib, but then, there's no convenient way to include headers into the project. and in case of building it as a part of your project? there is no convenient way to add all required includes/sourcs either.
Should I add a `.pri` file to address this issue, or is there a way to use it I can't figure out?

**Comment by falceeffect** [comment]
[One](https://github.com/falceeffect/Clipper) of my projects uses the lib. I'm sure that's not a very good way, but I just clone and build the lib as configure step for Clipper's build process. To add the headers dir, you can use something like
 `INCLUDEPATH += $$PWD/libs/UGlobalHotkey`

**Comment by MOZGIII** [comment]
Oh wow, that's really not very good. I suggest using submodules for that.
Also check out how I'm using `.pri` files: https://github.com/MOZGIII/QWidgetsListWidget. This may be a good idea to create rethink the way your project may be used by other project.
I guess, there are two good options here: to get it as a submodule, then to build it as a lib and then to link with it, or with a submodule and direct source code inclusion and compilation as a main build process part.
You could then make a `.pri` for people to include for use with a single build process mode, and set valide that a `.pro` file is set up corretly for subproject build.

**Comment by falceeffect** [comment]
Thanks, I'll definitely look into it tomorrow.

**Comment by falceeffect** [comment]
@bakwc What would you say? Shall we add that `.pri` file or try something else?

**Comment by bakwc** [comment]
Почему-бы нет, можно добавить.. правда придется следить ещё за одним файлом.
ЗЫ система сборки у qt-а - говно.
ЗЗЫ правильней вообще всю эту либу отрефакторить и попытаться законтрибутить в сам qt.

**Comment by MOZGIII** [comment]
Check this out. :P
This should address all discussed ways of using the code.

**Comment by bakwc** [comment]
Вроде норм но надо UGLOBALHOTKEY_NOEXPORT где-то объявить.

**Comment by MOZGIII** [comment]
I don't think those `.pri` files is the place for that. We could introduce another one, with this define and both header and source includes. I'll make one now.

**Comment by MOZGIII** [comment]
Updated #7

**Comment by falceeffect** [comment]
@bakwc shall I merge this one?

**Comment by bakwc** [comment]
Ага, то что надо! MOZGIII, спс.
Мержи.
ЗЫ falceeffect я тебе в скайп отписал ответь чтонить..
